#sdk: "/Users/Ryota/.rvm/gems/ruby-1.9.3-p194@rhodes/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: ringtones
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.ringtones
  BundleURLScheme: ringtones
wp:
  productid: '5aa70f30-bcdc-012f-2517-3c07542aa8a3'
symbian:
  uid: '0xec0a414b'
android:
  version: 2.1

extensions: ["json", "another-extension"]
